source/WebDevelopers/WebDevelopers/Models/contactModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebDevelopers.Models
{
    public class contactModel
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }
        public string Message { get; set; }

    }
}

source/WebDevelopers/WebDevelopers/Controllers/ContactSurfaceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Umbraco.Web.Mvc;
using WebDevelopers.Models;

namespace WebDevelopers.Controllers
{
    public class ContactSurfaceController : SurfaceController
    {
        public ActionResult ShowForm()
        {
            contactModel myModel = new contactModel();
            return PartialView("ContactForm", myModel);

        }
        public ActionResult HandleFormPost(contactModel model)
        {
            var newComment = Services.ContentService.CreateContent(model.Name + "." + DateTime.Now, CurrentPage.Id, "ContactFormula");
            newComment.SetValue("emailForm", model.Email);
            newComment.SetValue("contactName", model.Name);
            newComment.SetValue("contactMessage", model.Message);
            Services.ContentService.SaveAndPublishWithStatus(newComment);
            return RedirectToCurrentUmbracoPage();
        }
    }
}

source/WebDevelopers/WebDevelopers/Views/About.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
}
<div class="container-fluid">
		<div class="container">
			<h1>@CurrentPage.Name</h1>
	<br />
			
	@CurrentPage.about
			@CurrentPage.GetGridHtml("aboutPage", "bootstrap3")
		
			
	
			</div>
			</div>

source/WebDevelopers/WebDevelopers/Views/Articles.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
}
<div class="container-fluid">
		<div class="container">
			<h1>@CurrentPage.Name</h1>
	<br />
			
	@CurrentPage.articlesBodytext
	
			</div>
			</div>

source/WebDevelopers/WebDevelopers/Views/ArticlesItems.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
}
<div class="container-fluid">
		<div class="container">
			<div class="col-lg-8 pull-left">
			<h2>@CurrentPage.Name</h2>
	<br />
				@CurrentPage.articleContents
			</div>
				<h4>Published at: @Model.Content.CreateDate</h4>
			    <h4>LastEdited at: @Model.Content.UpdateDate</h4>
			
				</div>
			</div>

source/WebDevelopers/WebDevelopers/Views/ArticlesMain.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
	}

			<h1>@CurrentPage.Name</h1>
			@CurrentPage.articlesBodytext
			
				<div id="main-container">
					 <div id="main" class="wrappr clearfix">
						 <section>
						 <h2>@Umbraco.Field("articleTilte")</h2>
						 <p>@Umbraco.Field("articlesBodytext")<p>
						 @Umbraco.RenderMacro("ListArticles")
						  </section>
						 </div>
						 </div>
					

source/WebDevelopers/WebDevelopers/Views/ContactForm.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<WebDevelopers.Models.contactModel>

@using (Html.BeginUmbracoForm<WebDevelopers.Controllers.ContactSurfaceController>("HandleFormPost"))
{
    <div class="form-group">
        <label for="emailform">Email</label>
        @Html.TextBoxFor(x => x.Email, new { @class = "emailForm", @required = "required", placeholder = "Email" })
        </div>

        <div class="form-group">
            <label for="nameForm">Name</label>
            @Html.TextBoxFor(x => x.Name, new { @class = "nameForm", @required = "required", placeholder = "Name" })
           </div>

             <br />
            <div class="form-group">
                <label for="messageForm">Message</label>
                <br />
                @Html.TextAreaFor(x => x.Message, new { @class = "messageForm", @required = "required", placeholder = "Message" })
                </div>
                    <br />
                    <div class="form-group">
                       <button type="submit" class="btn btn-info">Submit</button>
                       </div>
                    }

source/WebDevelopers/WebDevelopers/Views/ContactFormula.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage

@{
    Layout = "Master.cshtml";
}

source/WebDevelopers/WebDevelopers/Views/ContactPage.cshtml
@using WebDevelopers.Controllers;
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{

    Layout = "Master.cshtml";
}

<div class="container-fluid">

    <div class="container">

        <h1>@CurrentPage.Name</h1>

        @Html.Action("ShowForm", "ContactSurface")

    </div>

</div>
         
          

source/WebDevelopers/WebDevelopers/Views/Home.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
}

<link rel="stylesheet" type="text/css" href="/css/Custom.css" />
	<body>
		<div class="container-fluid">
		<div class="container">
			<h1>Aarhus Web Developers</h1>
	<br />
         
			@CurrentPage.home
			@CurrentPage.GetGridHtml("pageImage", "bootstrap3")
			</div>
			</div>
			</body>
			

source/WebDevelopers/WebDevelopers/Views/Login.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
}
<div class="container-fluid">
		<div class="container">
<h1>@CurrentPage.Name</h1>
			
	@if (!Members.GetCurrentLoginStatus().IsLoggedIn) {
		@Html.Partial("Login");
	}
	else 
	{
		@Html.Partial("LoginStatus");
		
	}

			
			</div>
			</div>

source/WebDevelopers/WebDevelopers/Views/MacroPartials/ListArticles.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage

@* OrderBy() takes the property to sort by and optionally order desc/asc *@

@foreach (var page in CurrentPage.Children.Where("Visible").OrderBy("CreateDate desc"))
{ 
    <div class="article">
        <div class="articletitle"><a href="@page.Url">@page.Name</a></div>
        <div class="articlepreview">@Umbraco.Truncate(@page.ArticleContents,100) <a href="@page.Url">Read More..</a></div>
    </div>
    <hr/>
}

source/WebDevelopers/WebDevelopers/Views/MacroPartials/Member List.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage


@*
    This snippet creates links for every single page (no matter how deep) below
    the page currently being viewed by the website visitor, displayed as nested unordered html lists.
*@

@{ var selection = CurrentPage.Children.Where("Visible"); }

@* Ensure that the Current Page has children *@
@if (selection.Any())
{
    @* Get the first page in the children, where the property umbracoNaviHide is not True *@
    var naviLevel = CurrentPage.FirstChild().Where("Visible").Level;

    @* Add in level for a CSS hook *@
    <ul class="level-@naviLevel">
        @* For each child page  where the property umbracoNaviHide is not True *@
        @foreach (var item in selection)
        {
            <li>
                <a href="@item.Url">@item.Name</a>

                @* if this child page has any children, where the property umbracoNaviHide is not True *@
                @if (item.Children.Where("Visible").Any())
                {
                    @* Call our helper to display the children *@
                    @childPages(item.Children)
                }
            </li>
        }
    </ul>
}


@helper childPages(dynamic selection)
{
    @* Ensure that we have a collection of pages *@
    if (selection.Any())
    {
        @* Get the first page in pages and get the level *@
        var naviLevel = selection.First().Level;

        @* Add in level for a CSS hook *@
        <ul class="level-@(naviLevel)">
            @foreach (var item in selection.Where("Visible"))
            {
                <li>
                    <a href="@item.Url">@item.Name</a>

                    @* if the this page has any children, where the property umbracoNaviHide is not True *@
                    @if (item.Children.Where("Visible").Any())
                    {
                        @* Call our helper to display the children *@
                        @childPages(item.Children)
                    }
                </li>
            }
        </ul>
    }
}

source/WebDevelopers/WebDevelopers/Views/MacroPartials/listProjects.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage


@{ var selection = CurrentPage.Children.Where("Visible").OrderBy("CreateDate desc"); }
@* OrderBy() takes the property to sort by and optionally order desc/asc *@

<ul>
    @foreach (var item in selection)
    {
        <li><a href="@item.Url">@item.Name</a></li>
    }
</ul>

source/WebDevelopers/WebDevelopers/Views/Master.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = null;
}


<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
      <link href="~/css/lightbox.css" rel="stylesheet" />
      <link href="~/css/Custom.css" rel="stylesheet" />
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">

	
	        <title>@CurrentPage.PageTitle | @CurrentPage.SiteName</title>

	
        </head>
	
<body>
	
    <div class="container-fluid">
        <div class="container">
@Html.Partial("Navigation")
		</div>
    </div>
       

    <div class="container-fluid">
        <div class="container">
            @RenderBody()
        </div>
    </div>
			 <div class="container-fluid">
        <div class="container">
			<footer>
			<h6>@Umbraco.Field("footerText", recursive: true)</h6>
			</footer>
			 </div>
    </div>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <script src="~/Scripts/lightbox.js"></script>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
</body>
</html>

source/WebDevelopers/WebDevelopers/Views/Members.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@using Umbraco.Core;
@using Umbraco.Core.Models;
@using Umbraco.Core.Services;
@{
    Layout = "Master.cshtml";
}
@{
var memberService =
ApplicationContext.Current.Services.MemberService;

var members = memberService.GetMembersByGroup("Active");
}
@{
var memberService1 =
ApplicationContext.Current.Services.MemberService;

var members1 = memberService1.GetMembersByGroup("Prospect");
}

<div class="container-fluid">
		<div class="container">
			<h1>@CurrentPage.Name</h1>
			@foreach (var member in members) 
{
<p>
@(member.GetValue("firstname") + " "
+ member.GetValue("lastname")) <br/>
@member.GetValue("address")<br />
@(member.GetValue("zip") + " "
+ member.GetValue("city"))
Mobile: @member.GetValue("mobile")<br />
</p>
}
	@foreach (var member2 in members1) 
{
<p>
@(member2.GetValue("firstname") + " "
+ member2.GetValue("lastname")) <br/>
Mobile: @member2.GetValue("mobile")<br />
</p>
}

			</div>
			</div>

source/WebDevelopers/WebDevelopers/Views/Partials/Grid/Bootstrap2.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@* 
    Razor helpers located at the bottom of this file
*@

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;
    
    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row, true);
                    }
                </div>
            }   
        }else { 
            <div class="container">
                <div class="row clearfix">
                    @foreach (var s in Model.sections) {
                        <div class="grid-section">
                            <div class="@("span" + s.grid) column">
                                @foreach (var row in s.rows) {
                                    @renderRow(row, false);
                                }
                            </div>
                        </div>
                    }
                </div>
            </div>   
        }
    </div>
}

@helper renderRow(dynamic row, bool singleColumn){
    <div @RenderElementAttributes(row)>
        @Umbraco.If(singleColumn, "<div class='container'>")
        <div class="row clearfix">
            @foreach ( var area in row.areas ) {
            <div class="@("span" + area.grid) column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
        @Umbraco.If(singleColumn, "</div>")
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties()) {
                attrs.Add(property.Name + "=\"" + property.Value.ToString() + "\"");
            }
                
        JObject style = contentItem.styles;

        if (style != null) { 
        var cssVals = new List<string>();
        foreach (JProperty property in style.Properties())
            cssVals.Add(property.Name + ":" + property.Value.ToString() + ";");

        if (cssVals.Any())
            attrs.Add("style=\"" + string.Join(" ", cssVals) + "\"");
        }
            
        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

source/WebDevelopers/WebDevelopers/Views/Partials/Grid/Bootstrap3.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@* 
    Razor helpers located at the bottom of this file
*@

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;
    
    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row, true);
                    }
                </div>
            }   
        }else { 
            <div class="container">
                <div class="row clearfix">
                    @foreach (var s in Model.sections) {
                        <div class="grid-section">
                            <div class="col-md-@s.grid column">
                                @foreach (var row in s.rows) {
                                    @renderRow(row, false);
                                }
                            </div>
                        </div>
                    }
                </div>
            </div>   
        }
    </div>
}

@helper renderRow(dynamic row, bool singleColumn){
    <div @RenderElementAttributes(row)>
        @Umbraco.If(singleColumn, "<div class='container'>")
        <div class="row clearfix">
            @foreach ( var area in row.areas ) {
            <div class="col-md-@area.grid column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
        @Umbraco.If(singleColumn, "</div>")
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties()) {
                attrs.Add(property.Name + "=\"" + property.Value.ToString() + "\"");
            }
                
        JObject style = contentItem.styles;

        if (style != null) { 
        var cssVals = new List<string>();
        foreach (JProperty property in style.Properties())
            cssVals.Add(property.Name + ":" + property.Value.ToString() + ";");

        if (cssVals.Any())
            attrs.Add("style=\"" + string.Join(" ", cssVals) + "\"");
        }
            
        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

source/WebDevelopers/WebDevelopers/Views/Partials/Grid/Editors/Base.cshtml
@model dynamic
@using Umbraco.Web.Templates

@functions {
    public static string EditorView(dynamic contentItem)
    {
        string view = contentItem.editor.render != null ? contentItem.editor.render.ToString() : contentItem.editor.view.ToString();
        view = view.ToLower().Replace(".html", ".cshtml");
        
        if (!view.Contains("/")) {
            view = "grid/editors/" + view;
        }

        return view;
    }
}
@try
{
    string editor = EditorView(Model);                                                       
    <text>@Html.Partial(editor, (object)Model)</text>
}
catch (Exception ex) { 
<pre>@ex.ToString()</pre>
}

source/WebDevelopers/WebDevelopers/Views/Partials/Grid/Editors/Embed.cshtml
@model dynamic
@using Umbraco.Web.Templates
@Html.Raw(Model.value)

source/WebDevelopers/WebDevelopers/Views/Partials/Grid/Editors/Macro.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates


@if (Model.value != null)
{
    string macroAlias = Model.value.macroAlias.ToString();
    ViewDataDictionary parameters = new ViewDataDictionary();
    foreach (dynamic mpd in Model.value.macroParamsDictionary)
    {
        parameters.Add(mpd.Name, mpd.Value);
    }

    <text>
        @Umbraco.RenderMacro(macroAlias, parameters)
    </text>
}

source/WebDevelopers/WebDevelopers/Views/Partials/Grid/Editors/Media.cshtml
@model dynamic
@using Umbraco.Web.Templates

@if (Model.value != null)
{   
    var url = Model.value.image;
    if(Model.editor.config != null && Model.editor.config.size != null){
        url += "?width=" + Model.editor.config.size.width;
        url += "&height=" + Model.editor.config.size.height;

        if(Model.value.focalPoint != null){
            url += "&center=" + Model.value.focalPoint.top +"," + Model.value.focalPoint.left;
            url += "&mode=crop";
        }
    }
    
    <img src="@url" alt="@Model.value.altText">
    
    if (Model.value.caption != null)
    {
        <p class="caption">@Model.value.caption</p>
    }
}

source/WebDevelopers/WebDevelopers/Views/Partials/Grid/Editors/Rte.cshtml
@model dynamic
@using Umbraco.Web.Templates

@Html.Raw(TemplateUtilities.ParseInternalLinks(Model.value.ToString()))

source/WebDevelopers/WebDevelopers/Views/Partials/Grid/Editors/Textstring.cshtml
@model dynamic
@using Umbraco.Web.Templates

@if (Model.editor.config.markup != null)
{
    string markup = Model.editor.config.markup.ToString();

    markup = markup.Replace("#value#", Model.value.ToString());
    markup = markup.Replace("#style#", Model.editor.config.style.ToString());

    <text>
        @Html.Raw(markup)
    </text>
}
else
{
    <text>
        <div style="@Model.editor.config.style">@Model.value</div>
    </text>
}

source/WebDevelopers/WebDevelopers/Views/Partials/Login.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage


@using System.Web.Mvc.Html
@using ClientDependency.Core.Mvc
@using Umbraco.Web
@using Umbraco.Web.Models
@using Umbraco.Web.Controllers

@{
    var loginModel = new LoginModel();
    
    Html.EnableClientValidation();
    Html.EnableUnobtrusiveJavaScript();
    Html.RequiresJs("/umbraco_client/ui/jquery.js");
    Html.RequiresJs("/umbraco_client/Application/JQuery/jquery.validate.min.js");
    Html.RequiresJs("/umbraco_client/Application/JQuery/jquery.validate.unobtrusive.min.js");
}

@* NOTE: This RenderJsHere code should be put on your main template page where the rest of your script tags are placed *@
@Html.RenderJsHere()

@using (Html.BeginUmbracoForm<UmbLoginController>("HandleLogin"))
{
    <fieldset>
      
        
        @Html.ValidationSummary("loginModel", true)

        @Html.LabelFor(m => loginModel.Username)
        @Html.TextBoxFor(m => loginModel.Username)
        @Html.ValidationMessageFor(m => loginModel.Username)
        <br />

        @Html.LabelFor(m => loginModel.Password)
        @Html.PasswordFor(m => loginModel.Password)
        @Html.ValidationMessageFor(m => loginModel.Password)
        <br />

        <button>Login</button>
    </fieldset>  
}

source/WebDevelopers/WebDevelopers/Views/Partials/LoginStatus.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage

@using System.Web.Mvc.Html
@using ClientDependency.Core.Mvc
@using Umbraco.Web
@using Umbraco.Web.Models
@using Umbraco.Web.Controllers

@{
    var loginStatusModel = Members.GetCurrentLoginStatus();

    Html.EnableClientValidation();
    Html.EnableUnobtrusiveJavaScript();
    Html.RequiresJs("/umbraco_client/ui/jquery.js");
    Html.RequiresJs("/umbraco_client/Application/JQuery/jquery.validate.min.js");
    Html.RequiresJs("/umbraco_client/Application/JQuery/jquery.validate.unobtrusive.min.js");

    var logoutModel = new PostRedirectModel();
    
    @*
        Here you can specify a redirect URL for after logging out, by default umbraco will simply
        redirect to the current page. Example to redirect to the home page:
        
        logoutModel.RedirectUrl = "/"; 
    *@
}

@* NOTE: This RenderJsHere code should be put on your main template page where the rest of your script tags are placed *@
@Html.RenderJsHere()

@if (loginStatusModel.IsLoggedIn)
{
    <p>You are currently logged in as @loginStatusModel.Name</p>

    using (Html.BeginUmbracoForm<UmbLoginStatusController>("HandleLogout"))
    {
         <fieldset>
             <legend>Logout</legend>
             <button>Logout</button>
         </fieldset>
    
        @Html.HiddenFor(m => logoutModel.RedirectUrl)
    }
}

source/WebDevelopers/WebDevelopers/Views/Partials/Navigation.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage


@*
    This snippet displays a list of links of the pages immediately under the top-most page in the content tree.
    This is the home page for a standard website.
    It also highlights the current active page/section in the navigation with the css class "current".
*@
	@{
   var root = CurrentPage.AncestorOrSelf(1);
}
 
          <ul class="nav navbar-nav">
            <li class="@(CurrentPage.Name == root.Name ? "selected" : null)">
                <a href="/">@root.Name</a>
            </li>
				
            @foreach (var menuItem in root.Children.Where("Visible"))
            {
				
                <li class="@(menuItem.IsAncestorOrSelf(CurrentPage) ? "selected" : null)">
                    <a href="@menuItem.Url">@menuItem.Name</a>
                </li>
            }
        </ul>
		

source/WebDevelopers/WebDevelopers/Views/ProjectItems.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
}
@Umbraco.Field("projectTitle")
 @Umbraco.Field("projectContext")

source/WebDevelopers/WebDevelopers/Views/ProjectsMain.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
}
<div class="container-fluid">
		<div class="container">
			<h1>@CurrentPage.Name</h1>
	<br />
<h3>@Umbraco.Field("projectTitle")</h3>
			@Umbraco.RenderMacro("listProjects")
			
			</div>
			</div>
			

source/WebDevelopers/WebDevelopers/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

source/WebDevelopers/WebDevelopers/Views/TextPage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
}
<div class="container-fluid">
	<div class="container">
<h1>Access Forbidden</h1>
				</div>
		</div>